debug: true
server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sdeven-sparrow
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/develop?serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  redis:
    host: 127.0.0.1
    password: 123456
    database: 0
    timeout: 60000
    ssl: false
    redisson:
      mode: single
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          subscriptionsPerConnection: 5
          clientName: "sdeven-redis"
          address: "redis://127.0.0.1:6379"
          password: 123456
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 32
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 1
        nettyThreads: 1
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"